[[pages]]
path = "sumPaperPage.py"
name = "Summarize Paper"
icon = "ğŸ“ƒ"

[[pages]]
path = "hisSumPage.py"
name = "Summarize History"
icon = "ğŸ“"
url_path = "his_sum" # You can override the default url path for a page

[[pages]]
path = "chatWithPapers.py"
name = "Chat with AI !"
icon = "ğŸ¤–"
url_path = "chat"