[[pages]]
path = "summarize_paper_page.py"  # Äá»•i tÃªn file Ä‘á»ƒ mÃ´ táº£ rÃµ hÆ¡n
name = "TÃ³m Táº¯t TÃ i Liá»‡u"
icon = "ğŸ“ƒ"

[[pages]]
path = "summarize_history_page.py"  # Äá»•i tÃªn file Ä‘á»ƒ mÃ´ táº£ rÃµ hÆ¡n
name = "BÃ i BÃ¡o ÄÃ£ TÃ³m Táº¯t"
icon = "ğŸ“"
url_path = "tomtat"  # Báº¡n cÃ³ thá»ƒ ghi Ä‘Ã¨ Ä‘Æ°á»ng dáº«n url máº·c Ä‘á»‹nh cho trang nÃ y

[[pages]]
path = "chat_with_ai.py"  # Äá»•i tÃªn file Ä‘á»ƒ mÃ´ táº£ rÃµ hÆ¡n
name = "AI Chat"
icon = "ğŸ¤–"
url_path = "tro_chuyen"
